baseurl: 'https://upframe.io/'
disqusShortname: upframe
languageCode: en
paginate: 15
pluralizelisttitles: false
removePathAccents: true
title: Upframe
pygmentsStyle: github

params:
  Analytics: 93489376-1
  image: upframe
  Description: >-
    Upframe 2.0 is on its way.
  Social:
    Facebook: upframe
    GitHub: upframe
    Instagram: upframe
    Twitter: upframehq
  Webmaster:
    Bing: B471CBBC9EF6900039C6BBF251EF277C
    Google: nVQ4_x6m6ZTRAzclMPNxpB0iMgK-xoIj_d-l85u32nY

backend:
  name: git-gateway
  branch: master
